### ISSUE TITLE
jwplayer example not loading

### ISSUE THREAD

**Issue by lordfenixnc** [libass/JavascriptSubtitlesOctopus#102]
very noob.   have a working website and trying to get  ass subtitles working.  was trying to view your JW example and it wont load.   Hoping to figure out my best options  and currently using  JWplayer8.

**Comment by TheOneric** [comment]
Yup, the link to the JWPlayer library broke. I don't know how/why this was originally added, but it appears JWPlayer is a commercial offering and presumably the trial period for our link ended. The JWPlayer-demo has now been removed from the page, but the integration code can still be found in the wiki.

**Comment by StoneyEagle** [comment]
@TheOneric I've been using this package for a few years now.
Are you interested in a license key for the example page? I'll be happy to donate one.

**Comment by starkana** [comment]
The best license key is open source.

**Comment by TheOneric** [comment]
Thanks for the offer, but I don't think this would be worthwhile: Any new library link will again be publicly visible in the sources, probably be copied by others and might thus get banned even if someone were paying for a single license. The code for how to integrate with JWPlayer is still [availble in the wiki](https://github.com/libass/JavascriptSubtitlesOctopus/wiki/Integration-into-third-party-video-frameworks#jwplayer) and we have a lot of other demo players on our example page.

**Comment by StoneyEagle** [comment]
@TheOneric Sure no worries.
