### ISSUE TITLE
Future fontconfig versions ⪈2.13.94 won't need the fcstat patch

### ISSUE THREAD

**Issue by vadimkantorov** [libass/JavascriptSubtitlesOctopus#103]
I found they have an accessible bug tracker at https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues and was thinking to report it there

https://github.com/libass/JavascriptSubtitlesOctopus/blob/master/build/patches/fontconfig/0003-fix-fcstats-emscripten.patch

I'm using your patch for compiling TexLive under emscripten: https://github.com/busytex/busytex/blob/main/fontconfig_emcc.patch . Thanks for your patch!

**Comment by TheOneric** [comment]
Thanks @vadimkantorov for looking into this and contacting Fontconfig! As it turned out though, the version of emscripten we previously used, had a linker bug which made it not work even after the fix at Fontconfig’s side, but this should now be sorted out after upgrading emscripten.
