### ISSUE TITLE
Feature request:  Load Subtitles from Index.m3u8

### ISSUE THREAD

**Issue by lordfenixnc** [libass/JavascriptSubtitlesOctopus#104]
would it be possible for it to pull list of subtracks from HLS index?

**Comment by TheOneric** [comment]
JSO is only a subtitle renderer which can be integrated into players, not a full media player itself. As such it never sees the whole media file or the m3u8 index file, only the subtitle data. Any m3u8 parsing would need to be implemented in a player with the ability to forward subtitle data to JSO.
See also our [multi-track example](https://libass.github.io/JavascriptSubtitlesOctopus/mediaelement.html) *(source is in the `gh-pages` branch)* for working with multiple subtitle tracks.
