### ISSUE TITLE
I wish you will make a online demo  

### ISSUE THREAD

**Issue by kid1485** [libass/JavascriptSubtitlesOctopus#149]
I wish you will make a online demo about adding ASS_Event Object, ASS_Style Object to change subtitles's font size,color,.....Sorry,i don't know how to add it in code because i am amateur

**Comment by TheOneric** [comment]
Working directly (or well, via simple js wrappers)* with `ASS_Event`, `ASS_Style etc is only useful in some special cases and is definitely an advanced use case which requires care and knowledge of not just JSO's but also libass' API requirements (see [here](https://github.com/libass/libass/blob/master/libass/ass_types.h) and [here](https://github.com/libass/libass/blob/master/libass/ass.h)) else there can be severe problems.

There's no generally useful demo I can think of (apart from emulating streaming ASS, but htat's better solved another way) and any demo would need to be littered with comments explaining why this must or must not be done a particular way and refer to libass' docs. Hence I'm not planning to add such a demoand judging by the lack of othe responses it appears nobody else does either. If you really need it, look at libass' docs for explanations.
