### ISSUE TITLE
Feature request: Support effect in subtitles ass file

### ISSUE THREAD

**Issue by kid1485** [libass/JavascriptSubtitlesOctopus#150]
Request :Support effect in subtitles ass file .For example:{\i1}....{\i} ,... Currently,it's only add subtitles to video without effect

**Comment by TheOneric** [comment]
All ASS effects supported by libass – including `\i` – *are* already supported; see e.g. one of our demos: https://libass.github.io/JavascriptSubtitlesOctopus/videojs.html
