### ISSUE TITLE
SubtitlesOctopus Nextjs Runtime Error

### ISSUE THREAD

**Issue by Abdullah-988** [libass/JavascriptSubtitlesOctopus#157]
I've been trying to solve this problem since forever
when using SubtitlesOctopus with Nextjs project I always get errors like

![image](https://user-images.githubusercontent.com/77278705/232349737-a336787f-9b6e-4bdc-8e8b-856afb727f5c.png)

I'm using Nextjs With Typescript
My code:
```javascript
// Player.tsx

import { useEffect, useRef } from "react";
// @ts-ignore
import SubtitlesOctopus from "libass-wasm";

const MainDomain = "https://cdn..../"; // Basically my CDN url

type PlayerProps = {
  eng: string;
};

export default function Player({ eng }: PlayerProps) {

 useEffect(() => {
    Subtitles();
  }, []);

  function Subtitles() {
    var options = {
      video: document.querySelector("video"),
      subUrl: MainDomain + eng,
      workerUrl: new URL("libass-wasm/dist/js/subtitles-octopus-worker.js", import.meta.url)
    };

    var instance = new SubtitlesOctopus(options);
  }

  return <video />;
}
``` 

I would be appreciated If someone know how to solve this issue or If someone can make a repo example of how to use  SubtitlesOctopus with Nextjs Typescript

Thank You!

**Comment by zoriya** [comment]
Subtitle octopus does not provide typescript definitions (it could if #95 is merged one day). To include types, you must create a `.d.ts` file that define the type of SubtitleOctopus, you can refer to [this example](https://github.com/zoriya/Kyoo/blob/master/front/packages/ui/src/player/subtitle-octopus.d.ts) if you want.

*I created this file by copy-pasting the `type.d.ts` file from the PR and adding necessary lines to make it work from another project.*

**Comment by jeffuofa93** [comment]
Did you ever find a fix for this @Abdullah-988? Running into the same issue

**Comment by Abdullah-988** [comment]
@jeffuofa93 

It seems that the issue was workerUrl and its options

I fixed the issue by copying the dist folder from `libass-wasm/dist/js` to `.next` build and development folder using `copy-webpack-plugin` plugin in webpack

make sure you install `copy-webpack-plugin` package and
In `next.config.js` file:
```typescript
/** @type {import('next').NextConfig} */
const CopyWebpackPlugin = require("copy-webpack-plugin");

const nextConfig = {
  webpack: (config, { isServer }) => {
    // Add CopyWebpackPlugin to copy image files
    config.plugins.push(
      new CopyWebpackPlugin({
        patterns: [
          {
            from: "node_modules/libass-wasm/dist/js",
            to: `${isServer ? "../" : ""}static`,
          },
        ],
      })
    );

    return config;
  },
  reactStrictMode: true,
};

module.exports = nextConfig;
``` 

in the function:
```typescript
var instance = new SubtitlesOctopus({
    video: video,
    subUrl: MainDomain + Source,
    useLocalFonts: false,
    prescaleFactor: 3,
    availableFonts: {
      Font: "https://yourfonturl.com"
    },
    fallbackFont: "https://yourfonturl.com",
    fonts: [ "https://yourfonturl.com" ],
    workerUrl: "/_next/static/subtitles-octopus-worker.js" // <---------

    // or

    workerUrl: "/static/subtitles-octopus-worker.js"
  });
``` 

![image](https://user-images.githubusercontent.com/77278705/235798979-9edc3666-94cf-4bfd-8075-2be9a720e19b.png)
