### ISSUE TITLE
how to use directly with CDN?

### ISSUE THREAD

**Issue by freemedom** [libass/JavascriptSubtitlesOctopus#158]

**Comment by freemedom** [comment]
I understood how to use it after seeing the demo.

**Comment by lightninglu10** [comment]
Can you give an explanation, or example code?

**Comment by huanghaiyang** [comment]
you cant

**Comment by freemedom** [comment]
@huanghaiyang i find the method

**Comment by huanghaiyang** [comment]
> @huanghaiyang i find the method

how

**Comment by freemedom** [comment]
https://github.com/libass/JavascriptSubtitlesOctopus/issues/159#issuecomment-1685159485
@huanghaiyang
