### ISSUE TITLE
iOS 11.2.2 Worker error

### ISSUE THREAD

**Issue by nickfujita** [libass/JavascriptSubtitlesOctopus#20]
After the [iOS 11.2.2 update](https://support.apple.com/en-us/HT208401) released Jan 8th 2018 the library is now failing to operate properly, and is throwing the error shown below. It was tested in both the native safari browser and in a web view embedded in an application on device against the sample application in this repo. Any thoughts?

![screen shot 2018-01-09 at 6 02 10 pm](https://user-images.githubusercontent.com/6342442/34712746-4b40ebb0-f567-11e7-8fc0-557de937e78a.png)

**Comment by Dador** [comment]
Looks like it's connected to Spectre fixes in browsers.
So I suggest to build with -s ASSERTIONS=1 and see details about error.

Also it can be connected to [this bug](https://github.com/kripken/emscripten/issues/6042).

I think running [asmjs version](https://github.com/Dador/JavascriptSubtitlesOctopus/tree/master/js/asmjs) for Safari users should work as temporary workaround.

**Comment by nickfujita** [comment]
Confirmed working with just asm.js. From the comments in the bug you linked, the issues persists in 11.2.5 beta, so I'll just stick with asm.js for now. Thanks!

Might be good to leave this open until it gets resolved so others are aware.

**Comment by cobarx** [comment]
Looks like this only affects iOS 11.2.2-11.2.5, 11.3.0 and up should be fine. Adding this for my own notes.

**Comment by TheOneric** [comment]
> Looks like this only affects iOS 11.2.2-11.2.5

Meaning every affected setup has the ability to upgrade to 11.2.6, which is not affected. Given that and since iiuc it's not something on JSO's side, but rather due to an issue with an early Spectre/Meltdown-fix in iOS, it seems safe to close this now.
If I missed something and there's action required afterall, please say so and the issue will be reopened..
