### ISSUE TITLE
Manually change default position

### ISSUE THREAD

**Issue by ookami125** [libass/JavascriptSubtitlesOctopus#23]
So I've been working on a small project with VideoJS and everything works fine but I was wondering if it would be possible to change the default position of subtitles without changing the original subtitle file as the seek bar, if it pops up it covers the text.
![capture](https://user-images.githubusercontent.com/1776476/36356555-c51ce366-14c1-11e8-994c-896ad9ea1420.PNG)

**Comment by Dador** [comment]
Goshujinsama, you can add margin using [this function](https://github.com/libass/libass/blob/4cf8d6bb3e6b75f8215b69f697b6b5c05b1c1dd2/libass/ass.h#L313).
But I'm not sure about typesetting for labels, I suppose margin can break it.

P.S. Also, because subtitles loaded via javascript, you can edit it on client side.

**Comment by ookami125** [comment]
Editing them is possibility but I would like to avoid it if possible. That set margins function, how would I go about calling that function? This is actually the first project I've ever used that uses Emscripten. Just a rough idea should be enough, I can at least do a little research if I know where to start.

**Comment by ookami125** [comment]
Okay from a quick look over I see how it all works and I pretty much worked out how to do it, But now my big problem is I actually have to compile your code, because yeah just ripped it from your demo initially. So I'm going to go install Ubuntu on VirtualBox, Because one of the submodules you used emscripten on windows didnt like and also didnt like ubuntu subsystem for windows.
