### ISSUE TITLE
[Showcase] Flowplayer subtitle switching

### ISSUE THREAD

**Issue by Teranode** [libass/JavascriptSubtitlesOctopus#35]
For those of you wanting to switch subtitles using flowplayer:
You can use the default flowplayer subtitle plugin and within the api do add this:

```
flowplayer((api, root) => {
    ... /* other api code */
    flowplayer.bean.on(root, 'click', '.fp-subtitle-menu [data-subtitle-index]', function(ev) {
        var idx = ev.target.getAttribute('data-subtitle-index');
        if (idx === '-1') return window.subtitleInstance.freeTrack();
        window.subtitleInstance.setTrackByUrl(api.video.subtitles[idx].src)
    });
});
```

within the player instance itself you would put in the clip section: 
```
subtitles: [
   { "default": true, kind: "subtitles", srclang: "en", label: "English", src: this.subtitles[0].path }
], 
```

(i was using vue with this so `this.subtitles` would be a subtitle url) giving yall this, because flowplayer does not have subtitle events directly but you can use their bean handler to access it the same way.

**Comment by TheOneric** [comment]
Thanks!
To keep the issue tracker focused on actual issues, I've moved your example to the [wiki](https://github.com/libass/JavascriptSubtitlesOctopus/wiki/Integration-into-third-party-video-frameworks). Feel free to update it, add more, or perhaps send a patch to add it to the tests/demos on the [gh-pages](https://github.com/libass/JavascriptSubtitlesOctopus/tree/gh-pages) branch if you feel like it :)
