### ISSUE TITLE
Font isnt registered because of the name

### ISSUE THREAD

**Issue by Teranode** [libass/JavascriptSubtitlesOctopus#37]
there seems to be a small issue regarding the specific font names not being checked.

Lets say for instance i use: `EPSON 太丸ゴシック体Ｂ` this wont work because of `Ｂ`.
If i remove it then it'll work, im not sure what other characters are affected but that's the first instance i found.

**Comment by Teranode** [comment]
Here is an exampel font that isn't being read:
[F5AJJHR8.zip](https://github.com/Dador/JavascriptSubtitlesOctopus/files/4106657/F5AJJHR8.zip)

Name: Fj平成極太丸ゴシック体

**Comment by TheOneric** [comment]
Merged into #63 since it has more samples.

**Comment by TheOneric** [comment]
Correction: This has not directly something do to with the name but the font's encoding. It uses “SIJS” as encoding *(which affects not only the name, which is read as `FjïΩê¨ã…ëæä€ÉSÉVÉbÉNëÃ` but also the charmap making it unusable)*. All modern fonts use Unicode and that's the only font encoding libass currently supports. See: https://github.com/libass/libass/issues/531
You can recode the font with eg fontforge (remember to also sanitise the name) or use a native Unicode font.
