### ISSUE TITLE
Document what fast render mode does

### ISSUE THREAD

**Issue by rcombs** [libass/JavascriptSubtitlesOctopus#57]
This was added recently but it's not clear how it actually works, and what kind of loss can be expected when using it.

**Comment by LukePulverenti** [comment]
Thanks for updating the notes. What you've written suggests that provided no bitmaps fail, rendering will be equivalent. Is that correct?

**Comment by TFSThiagoBR98** [comment]
Yes, for example, it would be as a player, playing a video along with a heavy process, it will start to drop frames to keep playing without locking.
