### ISSUE TITLE
Brotli file error

### ISSUE THREAD

**Issue by Teranode** [libass/JavascriptSubtitlesOctopus#58]
When presenting the brotli (.br) file in `subUrl` i am met with this error:
`subtitles-worker.js:682 Uncaught (in promise) TypeError: content.split is not a function`
https://github.com/Dador/JavascriptSubtitlesOctopus/blob/4e1e0f2d61a23bfd4b2788fc075b86068b8c228e/dist/subtitles-octopus-worker.js#L7319

**Comment by TFSThiagoBR98** [comment]
@Teranode Please send the brotli file

**Comment by Teranode** [comment]
Here's a zip of the br file
[[DameDesuYo] ReZero kara Hajimeru Isekai Seikatsu (Shin Henshuu-ban) - 02 (1280x720 10bit EAC3) [E9C17853]_track3_eng.ass.zip](https://github.com/Dador/JavascriptSubtitlesOctopus/files/4042270/DameDesuYo.ReZero.kara.Hajimeru.Isekai.Seikatsu.Shin.Henshuu-ban.-.02.1280x720.10bit.EAC3.E9C17853._track3_eng.ass.zip)

**Comment by TheOneric** [comment]
Works now for me. If it wasn't already fixed before, #107 should have done the trick.
