### ISSUE TITLE
Can you help connect the script to the PlayerJS player?

### ISSUE THREAD

**Issue by Maximus2014** [libass/JavascriptSubtitlesOctopus#61]
Hello, can you help please connect the script to PlayerJS
Here is the link to the player: https://playerjs.com/en/
Api: https://playerjs.com/docs/q=api

**Comment by TFSThiagoBR98** [comment]
```js
var player = new Playerjs({id:"player", file:"video.mp4"});

function onPlay() {
    var video = document.getElementById(player.api("id")).querySelector("video");
    window.SubtitlesOctopusOnLoad = function () {
        var options = {
            video: video,
            subUrl: '/JavascriptSubtitlesOctopus/subtitles/test.ass',
            fonts: ['/JavascriptSubtitlesOctopus/fonts/Arial.ttf', '/JavascriptSubtitlesOctopus/fonts/TimesNewRoman.ttf'],
            //onReady: onReadyFunction,
            //debug: true,
            workerUrl: '/JavascriptSubtitlesOctopus/assets/js/subtitles-octopus-worker.js'
        };
        window.octopusInstance = new SubtitlesOctopus(options);
    };
    if (SubtitlesOctopus) {
        SubtitlesOctopusOnLoad();
    }
}
document.getElementById(player.api("id")).addEventListener("play", onPlay);
```

Try this

**Comment by Maximus2014** [comment]
Does not work

**Comment by Maximus2014** [comment]
> ```js
> var player = new Playerjs({id:"player", file:"video.mp4"});
> 
> function onReady() {
>     var video = document.getElementById(player.api("id")).querySelector("video");
>     window.SubtitlesOctopusOnLoad = function () {
>         var options = {
>             video: video,
>             subUrl: '/JavascriptSubtitlesOctopus/subtitles/test.ass',
>             fonts: ['/JavascriptSubtitlesOctopus/fonts/Arial.ttf', '/JavascriptSubtitlesOctopus/fonts/TimesNewRoman.ttf'],
>             //onReady: onReadyFunction,
>             //debug: true,
>             workerUrl: '/JavascriptSubtitlesOctopus/assets/js/subtitles-octopus-worker.js'
>         };
>         window.octopusInstance = new SubtitlesOctopus(options);
>     };
>     if (SubtitlesOctopus) {
>         SubtitlesOctopusOnLoad();
>     }
> }
> document.getElementById(player.api("id")).addEventListener("ready", onReady);
> ```
> 
> Try this

Does not work

**Comment by Teranode** [comment]
Try

```
function PlayerjsEvents(event, id, data){
    if(event==="init"){
        var video = document.querySelector("video");
        window.SubtitlesOctopusOnLoad = function () {
            var options = {
                video: video,
                subUrl: '/JavascriptSubtitlesOctopus/subtitles/test.ass',
                fonts: [
                    '/JavascriptSubtitlesOctopus/fonts/Arial.ttf',
                    '/JavascriptSubtitlesOctopus/fonts/TimesNewRoman.ttf'
                ],
                workerUrl: '/JavascriptSubtitlesOctopus/assets/js/subtitles-octopus-worker.js'
            };
            window.octopusInstance = new SubtitlesOctopus(options);
        };
        if (SubtitlesOctopus) {
            SubtitlesOctopusOnLoad();
        }
    }
}
```

**Comment by Maximus2014** [comment]
> function PlayerjsEvents(event, id, data){
>     if(event==="init"){
>         var video = document.querySelector("video");
>         window.SubtitlesOctopusOnLoad = function () {
>             var options = {
>                 video: video,
>                 subUrl: '/JavascriptSubtitlesOctopus/subtitles/test.ass',
>                 fonts: [
>                     '/JavascriptSubtitlesOctopus/fonts/Arial.ttf',
>                     '/JavascriptSubtitlesOctopus/fonts/TimesNewRoman.ttf'
>                 ],
>                 workerUrl: '/JavascriptSubtitlesOctopus/assets/js/subtitles-octopus-worker.js'
>             };
>             window.octopusInstance = new SubtitlesOctopus(options);
>         };
>         if (SubtitlesOctopus) {
>             SubtitlesOctopusOnLoad();
>         }
>     }
> }

thanks a lot, everything worked
