### ISSUE TITLE
createEvent broken by mutating strings

### ISSUE THREAD

**Issue by ThaUnknown** [libass/JavascriptSubtitlesOctopus#77]
adding an event with createEvent
```js
{
Duration: 4880,
Effect: "",
Layer: 0,
MarginL: 0,
MarginR: 0,
MarginV: 0,
Name: "",
ReadOrder: 0,
Start: 7870,
Style: 1,
Text: "Text."
}
```
for some reason creates an event that looks like:
```js
{
Duration: 4880,
Effect: "Text.",
Layer: 0,
MarginL: 0,
MarginR: 0,
MarginV: 0,
Name: "Text.",
ReadOrder: 0,
Start: 7870,
Style: 1,
Text: "Text."
}
```
breaking the entire renderer, adding more subtitles with the createEvent function overwrites the text, effect and name values of the previous events

**Comment by ThaUnknown** [comment]
are there any fixes for this? its becoming a serious issues for very well typesetted subs like [μtw-Kaleido] releases, which can be shown here: `60a5523d6380ed07ff63648b76324c6ca8192faf`, i currently work around this issue by building the sub file and passing it via `octopusInstance.setTrack()` but for videos with a few thousand subtitles it kills the service worker thread, even on high-end hardware!

**Comment by ThaUnknown** [comment]
@Dador

**Comment by TheOneric** [comment]
Can confirm this still happens with [current](https://github.com/libass/JavascriptSubtitlesOctopus/commit/9d22185464c7fb8471273609b63d8c3f29fac3dd) master.
On a side note though, you should **not** create events with a non-unique ReadOrder value. Your example sets `ReadOrder: 0` which would be valid if the track was empty before, but otherwise this has the potential to mess things up.

**Comment by TheOneric** [comment]
@TFSThiagoBR98: Seems like you added this in ec21ec32597a56ff18eee4935775d32d195270f2, do you know what the "best practce"-way of passing strings from JS to WASM is? This likely affects more than just `createEvent`.

**Comment by TFSThiagoBR98** [comment]
WebIDL uses this 2 generated functions:

```cpp
void EMSCRIPTEN_KEEPALIVE emscripten_bind_ASS_Event_set_Text_1(ASS_Event* self, char* arg0) {
  self->Text = arg0;
}
```

and its JS counterpart:

```js
ASS_Event.prototype['set_Text'] = ASS_Event.prototype.set_Text = /** @suppress {undefinedVars, duplicate} */function(arg0) {
  var self = this.ptr;
  ensureCache.prepare();
  if (arg0 && typeof arg0 === 'object') arg0 = arg0.ptr;
  else arg0 = ensureString(arg0);
  _emscripten_bind_ASS_Event_set_Text_1(self, arg0);
};
```

Also the `ensureString` function:
```js
function ensureString(value) {
  if (typeof value === 'string') {
    var intArray = intArrayFromString(value);
    var offset = ensureCache.alloc(intArray, HEAP8);
    ensureCache.copy(intArray, HEAP8, offset);
    return offset;
  }
  return value;
}
```

This uses the [intArrayFromString](https://emscripten.org/docs/api_reference/preamble.js.html#intArrayFromString) function but Emscripten also have the [stringToUTF8](https://emscripten.org/docs/api_reference/preamble.js.html#stringToUTF8), see [here](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#call-compiled-c-c-code-directly-from-javascript)
