### ISSUE TITLE
embedded mkv subtitles

### ISSUE THREAD

**Issue by Guizzu** [libass/JavascriptSubtitlesOctopus#79]
Hi, would it be possible to use a .ass that is embedded in a matroska video file?

AFAIK .mkv files works just like a .zip, with audio, video, subtitles and related files inside of it, wouldn't it be possible for the WASM to open and read the subtitle inside of the mkv?

**Comment by Yay295** [comment]
Technically yes, with things like Emscripten you can turn almost any standalone program into a web application, but it's not as simple as just unzipping the video container. The subtitle lines are actually interleaved throughout the file, so you would have to completely load the video file to get all of the subtitles. This sounds more like something that could be done with a separate program, and then once you've gotten just the subtitle file using that program you could feed it to this library like normal.

**Comment by qgustavor** [comment]
@Guizzoni Instead of using the patcher try using this: https://github.com/qgustavor/mkv-extract/

**Comment by Guizzoni** [comment]
Thanks @qgustavor, but I think that it would probably need the file fully downloaded before we could extract the .ass and use it within the web-player

**Comment by qgustavor** [comment]
It works using file streaming but currently needs a continuous stream. Maybe you can modify this to work with a seek-able stream (which is normal for a web player). By the way you will need to load the header of the file as fonts and subtitle styles are stored there.

**Comment by TheOneric** [comment]
JSO is only a subtitle renderer which can be integrated into players, not a full media player itself. As such it never sees the whole media file, only the subtitle data. Any mkv parsing would need to be implemented in a player with the ability to forward subtitle data to JSO.
Note that even if a player implements MKV parsing though, it *currently* would only work when the subtitle data is fully available at once. This working with streamed packets depends on #89.
