### ISSUE TITLE
Demo .mp4 file throws 404

### ISSUE THREAD

**Issue by grzegorzjudas** [libass/JavascriptSubtitlesOctopus#84]
Just happened to find this library and it looks cool - but after checking out the demo I found out it's not available ;)

**Comment by starkana** [comment]
Yep the maintainers abandoned it. All this work into creating it only to throw it all away. It ought to be under the spotlight and praised but it's in the dumpster instead.

**Comment by Yay295** [comment]
Three of the demos still work:
MediaElement.js Player Test with Multi-track - https://dador.github.io/JavascriptSubtitlesOctopus/mediaelement.html
Toaru Kagaku no Railgun S (Spring 2013) Karaoke Test - https://dador.github.io/JavascriptSubtitlesOctopus/railgun.html
Attack on Titan Season 3 Part 2 (Spring 2019) Stress Karaoke Test - https://dador.github.io/JavascriptSubtitlesOctopus/stress.html

**Comment by nopol10** [comment]
The library is great & works perfectly fine, you can even see it in action in a browser extension here: https://github.com/nopol10/nekocap (sorry for the self plug :P)

**Comment by grzegorzjudas** [comment]
The fact it's great and working fine doesn't unfortunately mean it's still maintained. Anyone has control over the demo URLs/this repo or forking is the way to go (if there already isn't one)?

**Comment by TFSThiagoBR98** [comment]
Fixed
