### ISSUE TITLE
Discuss: Transfer maintenance of this project into the libass org?

### ISSUE THREAD

**Issue by rcombs** [libass/JavascriptSubtitlesOctopus#90]
I noticed that this repo hasn't had any commits in over a year now; as the project has gained fairly decent adoption, it would probably benefit from a slightly larger maintainer community. @Dador, would you like to move this package into the libass org as an official libass-js binding? If you'd like to discuss in more detail, we're available at #libass on the Freenode IRC network.

If we don't hear back on this for a while, we'll probably assume this repo is abandoned and figure out future maintenance on our own, but I'd much rather work with the original authors on it if possible.

**Comment by Dador** [comment]
> @Dador, would you like to move this package into the libass org as an official libass-js binding?
Sounds good. I'll write to IRC channel.

Lately this project was maintained mostly by @TFSThiagoBR98 and @JustAMan.
I didn't worked on this project in a while but if you'll have any questions I'm happy to help.

**Comment by rcombs** [comment]
I see we missed you on IRC, but the transfer procedure is documented here: https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by Dador** [comment]
@rcombs, I couldn't send transfer request directly to the libass org, as:
> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

So I sent transfer request to you, so you can then transfer it to the libass org.

**Comment by TFSThiagoBR98** [comment]
I think is better to also transfer the [npm package](https://www.npmjs.com/package/libass-wasm/) as well, @rcombs can you create an org in npm?

**Comment by rcombs** [comment]
Created the `libass` org; you should have access.

**Comment by rcombs** [comment]
Closing this out, as the bulk of the transfer is complete.

**Comment by TFSThiagoBR98** [comment]
@rcombs can you give me permission to create packages in the org to make the transfer?

**Comment by rcombs** [comment]
Believe you should have it now.

**Comment by TFSThiagoBR98** [comment]
Ok, transfered

**Comment by Arnavion** [comment]
Sorry for the necro, but I just discovered this and wanted to say "Congratulations" :)
