### ISSUE TITLE
Missing `BUILD_AS_WORKER` parameter

### ISSUE THREAD

**Issue by cawa-93** [libass/JavascriptSubtitlesOctopus#98]
It seems here was missing [`BUILD_AS_WORKER`](https://emscripten.org/docs/api_reference/emscripten.h.html?highlight=build_as_worker#id6) and [`ENVIRONMENT=worker`](https://github.com/emscripten-core/emscripten/blob/dbf6d7141e0fc236688b4fdd59c5d93f9fc5fabb/src/settings.js#L605-L626). 
https://github.com/libass/JavascriptSubtitlesOctopus/blob/8309002ed6948ee62eec57852690f9efbcaf258f/Makefile#L306-L313

**Comment by TheOneric** [comment]
`ENVIRONMENT=worker` apparently was implied (with our other settings) in prior versions of emscripten, with the next emscripten bump it’ll be made explicit.

The `BUILD_AS_WORKER` documentation you’re linking is specific to `emscripten_create_worker(…)` which we do not use. Is there any documentation that this is a more general setting and if so what is the difference to `ENVIRONMENT=worker`?

**Comment by TheOneric** [comment]
`ENVIRONMENT=worker` was now added explicitly. As noted, `BUILD_AS_WORKER` appears to only apply to a emscripten-specific worker API not used by us, so probably not required. If that's incorrect, don't hesitate to point out why it should be set.
